version: "2"
services:
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb:2.0
    volumes:
      - ./influxdb/config/:/etc/influxdb2
      - ./influxdb/data/:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=roberts-house
      - DOCKER_INFLUXDB_INIT_BUCKET=bme680
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
  telegraf:
    image: telegraf:1.19
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - MQTT_ADDRESS=tcp://mqtt:1883
      - INFLUXDB_ADDRESS=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
  grafana:
    image: grafana/grafana:7.5.10
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - INFLUXDB_ADDRESS=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      