version: "2"
services:
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb:1.8
    restart: always
    volumes:
      - ./influxdb:/root/.influxdb
    environment:
      - INFLUXDB_ADMIN_USER_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_PASSWORD}
  telegraf:
    image: telegraf:1.19
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - MQTT_ADDRESS=tcp://mqtt:1883
      - INFLUXDB_ADDRESS=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
  grafana:
    image: grafana/grafana:9.0.3
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - INFLUXDB_ADDRESS=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
  cloudflare_tunnel:
    image: cloudflare/cloudflared:2022.7.1
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}