apiVersion: 1
datasources:
- orgId: 1
  version: 3
  name: InfluxDB
  type: influxdb
  access: proxy
  url: ${INFLUXDB_ADDRESS}
  user: ${INFLUXDB_USERNAME}
  database: ${INFLUXDB_DATABASE}
  secureJsonData:
    password: ${INFLUXDB_PASSWORD}